name: 'Publish image to GHCR on tag'

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: migration-tools
  cancel-in-progress: true

jobs:
  publish_image:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    with:
      image_name: "migration-tools"
      run_trivy_scan: true
      image_tag_generation: "version_git_tag"
      add_latest_tag: true
      container_registry: "ghcr.io"
      report_location: "Dockerfile"